export const SAVE_POLICY_REQUEST = 'SAVE_POLICY_REQUEST';
export const FETCH_POLICY_REQUEST = 'FETCH_POLICY_REQUEST';
export const UPDATE_POLICY_REQUEST = 'UPDATE_POLICY_REQUEST';
export const DELETE_POLICY_REQUEST = 'DELETE_POLICY_REQUEST';
export const POLICY_SUCCESS = 'POLICY_SUCCESS';
export const POLICY_FAILURE = 'POLICY_FAILURE';