export const SAVE_ROOMTYPE_REQUEST = 'SAVE_ROOMTYPE_REQUEST';
export const FETCH_ROOMTYPE_REQUEST = 'FETCH_ROOMTYPE_REQUEST';
export const UPDATE_ROOMTYPE_REQUEST = 'UPDATE_ROOMTYPE_REQUEST';
export const DELETE_ROOMTYPE_REQUEST = 'DELETE_ROOMTYPE_REQUEST';
export const ROOMTYPE_SUCCESS = 'ROOMTYPE_SUCCESS';
export const ROOMTYPE_FAILURE = 'ROOMTYPE_FAILURE';