export const SAVE_SERVICE_REQUEST = 'SAVE_SERVICE_REQUEST';
export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_FAILURE = 'SERVICE_FAILURE';